### ISSUE TITLE
--stop is not working anymore

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#238]
Not sure why but it appears that signal 10 is not being caught in Analysis driver.
Maybe this is due to Luigi ...
Signal 15 however is still being caught and kills the application as expected.
Either figure out how to fix signal 10 or use 15 in --stop

**Comment by mwhamgenomics** [comment]
Luigi does do some signal handling, but nothing with signal 10 as far as I can see. I don't remember why we were using signal 10 (Bus Error) in the first place. Are we sure we want to keep using it?

Edit: signal numbers in OSX and Linux are different, so 10 is actually `SIGUSR1` in Linux. We still probably only need signal 15, though (15 is `SIGTERM` in both OSX and Linux)

**Comment by mwhamgenomics** [comment]
This may be linked to #239

**Comment by mwhamgenomics** [comment]
A couple of things need clearing up:
- on Linux, `SIGINT` is 2, `SIGTERM` is 15 and `SIGUSR1` is 10
- OSX is similar, but `SIGUSR1` is 30
- This doesn't actually change anything, but it was a source of confusion during debugging.

It turns out that Luigi actually catches `SIGUSR1` and stops scheduling any new jobs, so it looks like nothing's happened, but the pipeline will actually stop cleanly. Given a simple linear pipeline of Task1 -> Task2 -> Task3, if you send a `SIGUSR1` while Task1 is running, Task1 will run to completion and then Luigi will output something like:

```
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 ran successfully:
    - 1 Task1()
* 2 were left pending, among these:
    * 2 was not granted run permission by the scheduler:
        - 1 Task2()
        - 1 Task3()
        ...

This progress looks :| because there were tasks that were not granted run permission by the scheduler

===== Luigi Execution Summary =====
```

We need to consider what functionality we want: do we want to let things stop gracefully as Luigi now does, or do we want to immediately stop everything currently running?
