### ISSUE TITLE
Error handling cleanup

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#239]
Luigi does some of its own Exception catching, meaning the `except Exception` block in analysis_driver.client never gets reached. Apart from being a bit untidy, it also means we haven't been getting crash reports since the latest version of the pipeline was put into production.

We should hook crash reports and stage failure notifications into `Stage.run` (since multiple concurrent stages could conceivably break in a single run), but leave pipeline failure notifications as they are in `client`.

**Comment by tcezard** [comment]
Because Luigi does its own exception handling it is not possible to raise an exception in a stage and catch it in the main thread.
It is currently preventing the aborted sequencing runs to be marked as aborted in our pipeline.
We need to set up a mechanism to register exceptions in luigi task so they can be queried in the main thread.
