### ISSUE TITLE
interop metrics parser should not pass NaN

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#381]
the interop summary can sometime output NaN in place of a value in its output.
The presence of NaN will make the JSON invalid so we need to avoid uploading these values.
The parser will be changed to replace NaN in the file with no entry being uploaded.

**Comment by mwhamgenomics** [comment]
The problem seems to be caused by Requests allowing the sending of invalid JSON. Suppose we call `rest_communication.patch_entry('endpoint', {'x': float('NaN')}, ...)`, eventually this data is serialised in`requests.PreparedRequest.prepare_body`:

```python
body = complexjson.dumps({'x': float('NaN')})
```

The `json` stdlib module (which requests aliases here as `complexjson`) has an `allow_nan` argument in `dumps` that defaults to True - if False, it raises a ValueError since [`NaN` is not an allowed JSON value](https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript). Here in Requests, however, it's left as True.

This then gets stored in the Rest API and when eventually queried by Datatables, Javascript does something like:
```javascript
JSON.parse("{'x': NaN}")
```
This results in a SyntaxError. Since Requests doesn't let us change the behaviour of `json.dumps`, we'll need to check the values produced by Interop.
