### ISSUE TITLE
Identify opened files which are not being closed

### ISSUE THREAD

**Issue by lukbut** [EdinburghGenomics/Analysis-Driver#395]
This issue arises from the run processing failure of 190429_E00375_0442_AHYW3WCCXY on 2nd May 2019. An OS error was reported, "Too many files open". 

The goal of this issue is to refactor the code of any opened files in analysis driver to ensure they are being closed after use and to reduce the chance of the mentioned OS error from occurring again.

**Comment by mwhamgenomics** [comment]
The error in the dataset above was `[Errno 23] Too many open files in system`. At the time of this problem occurring, we had a ulimit -n of 65535, and there was an explosion of bioinformatics activity, from ~25 to ~127 concurrent pipelines. This can be trended with the function below.

Open files on the main node per pipeline can be checked with `ps f --ppid <pid>` and `lsof -p <pid1,pid2...>`. Results per integration test were:

| test name             | max open files  | max open files * 127 |
| ----------------- | --------------- | --------------------- |
| bcbio                   | 210                    | 26670                         |
| demultiplexing     | 390                   | 49530                        |
| gatk4_var_calling | 712 -> 1189      | 90424 -> 151003       |

The large numbers of open files come from large numbers of shared memory files in `/dev/shm` (showing up as DEL in lsof) and Python standard lib modules. No pipes are being left open by `executor` or `rest_communication`.

EdinburghGenomics/Reporting-App#250 has been opened for trending bioinformatics activity.

Trending:
```python
def check_times(years, months, days, hours, mins):
    data_points = []
    for y, mo, d, h, mi in itertools.product(years, months, days, hours, mins):
        t = '%02i_%02i_%s_%02i:%02i:00' % (d, mo, y, h, mi)
        data = rest_communication.get_content(
            'analysis_driver_procs',
            where={'start_date': {'$lt': t}, 'end_date': {'$gt': t}}
        )
        data_points.append(
            '%s_%02i_%02i_%02i:%02i:00: %s' % (
                y, mo, d, h, mi, data['_meta']['total']
             )
        )
    return data_points

check_times([2019], [5], range(1, 9), range(9, 18), [0])
```

**Comment by mwhamgenomics** [comment]
The `/dev/shm/sem*` files seem to come from multprocessing Lock and Queue objects, which are used by Dataset, MostRecentProc and Toolset. A Lock object uses 1 shm file, and a Queue object uses 3. The numbers of shm files are inflated in integration tests because of the patching of assert methods with WrappedFunc objects, each of which has its own Lock object. So it looks like the open files are mainly standard lib and C modules, compounded by the number of worker processes we give to Luigi - this is set by the config `luigi.max_parallel_jobs`.

Looks like there's not much else that can be done here, short of trying to minimise the amount of logic done in multiprocessing.

**Comment by mwhamgenomics** [comment]
Closing as discussed.
